# Generated by Django 3.2.7 on 2021-09-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=2, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'contacts',
                'db_table': 'contacts',
            },
        ),
    ]
