# Generated by Django 3.2.7 on 2021-09-24 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=2, null=True)),
                ('image_path', models.ImageField(blank=True, default='media/no_image.png', null=True, upload_to='media/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picture_picture_created_by', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_device_fk', to='devices.devices')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picture_picture_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pictures',
                'verbose_name_plural': 'pictures',
            },
        ),
    ]
