# Generated by Django 3.2.7 on 2021-10-06 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sms_id', models.IntegerField(blank=True, null=True)),
                ('threadId', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('person', models.IntegerField(blank=True, null=True)),
                ('protocol', models.IntegerField(blank=True, null=True)),
                ('locked', models.BooleanField(blank=True, null=True)),
                ('read', models.BooleanField(blank=True, null=True)),
                ('seen', models.BooleanField(blank=True, null=True)),
                ('receivedDate', models.IntegerField(blank=True, null=True)),
                ('sentDate', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sms_sms_created_by', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_sms_fk', to='devices.devices')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sms_sms_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sms',
                'db_table': 'sms',
            },
        ),
    ]
